/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include<stdio.h>
#include<stdint.h>
#include<inttypes.h>

#define RELOAD           12499999 //25000000 -- 25MHz is the processor clocks

extern void initialise_monitor_handles(void);

void Systick_Config(uint32_t Reload);
void LED_init();
void SysTick_Handler();



uint32_t *pClkCtrlReg =   (uint32_t*)0x40023830;
		uint32_t *pPortIModeReg = (uint32_t*)0x40022000;
		uint32_t *pPortIOutReg =  (uint32_t*)0x40022014;

		//Systick
		uint32_t *pSYST_CSR = (uint32_t*)0xE000E010; // control and statis register
		uint32_t *pSYST_RVR = (uint32_t*)0xE000E014; //Reload Value register
		uint32_t *pSYST_CVR = (uint32_t*)0xE000E018; //Current Value register
		uint32_t *pSYST_CALIB = (uint32_t*)0xE000E01C; //Calibration Value register //Read only

		//NVIC Interrupt Priority register
		uint32_t *pNVIC_IPR0 = (uint32_t*)0xE000E400;

int main(void)
{
	 initialise_monitor_handles();
	printf("Program to blink LED using Interrupt \n");

	//Initialize and Configure GPIO for LED
		LED_init();

/**************************************************
 * Using Systick Interrupt to blink LED on every
 *
 */
		//Systick Configuration
		Systick_Config(RELOAD);

// Using the Polling method
#if 0
		while(1)
		{
			//3.SET 1st bit of the output data register to make I/O pin-1 as HIGH
			*pPortIOutReg |= ( 1 << 1);

			//introduce small human observable delay
			//This loop executes for 10K times
			for(uint32_t i=0 ; i < 300000 ; i++ );

			//Tun OFF the LED
			*pPortIOutReg &= ~( 1 << 1);

			for(uint32_t i=0 ; i < 300000 ; i++ );

		}

#endif


while(1)
{
}
	fflush(stdout);

}

void LED_init()
{
		//1. enable the clock for GPOIOI peripheral in the AHB1ENR (SET the 8th bit position)
			*pClkCtrlReg |= ( 1 << 8);

			//2. configure the mode of the IO pin as output
			//a. clear the 2nd and 3rd bit positions (CLEAR)
			*pPortIModeReg &= ~( 3 << 3);
			//b. make 3rd bit position as 1 (SET) for Pin-1. Each 2 bits represetn 1 Pin> Pin0=[1:0] Pin1=[3:2]
			*pPortIModeReg |= ( 1 << 2);

		//	*pPortIOutReg |= ( 1 << 1); // Turn-On LED

}

void Systick_Config(uint32_t Reload)
{// Disable Systick
			*pSYST_CSR |= 1 ; // Systick Disable

			//Configure SysTick_LOAD
					//clear the reg
					*pSYST_RVR &= ~(0xFFFFFF);
					*pSYST_RVR = Reload;
					printf("the Systick Reload Value Register holds value is %#X\n",*pSYST_RVR);
					printf("SYST_RVR in dec = %d\n",*pSYST_RVR);

				// Set Interrupt Priority

			//Configure Current Value register
					*pSYST_CVR &= ~(0xFFFFFFFF); //clear the register
					 printf("the Systick Current Value Register value is %#X\n",*pSYST_CVR);

				// Configure SYST_CSR
			*pSYST_CSR |= (1<<2) ; // Use Processor Clock
			*pSYST_CSR |= (1<<1) ; // Use interrupt enable
			*pSYST_CSR |= 1 ; // Systick Enable
			 printf("the Systick Status Register value is %#X\n",*pSYST_CSR);


}

#if 0
uint32_t SysTick_Init(uint32_t ticks)
{
  if ((ticks - 1UL) > SysTick_LOAD_RELOAD_Msk)
  {
    return (1UL);                                                   /* Reload value impossible */
  }

  SysTick->LOAD  = (uint32_t)(ticks - 1UL);                         /* set reload register */
  NVIC_SetPriority (SysTick_IRQn, (1UL << __NVIC_PRIO_BITS) - 1UL); /* set Priority for Systick Interrupt */
  SysTick->VAL   = 0UL;                                             /* Load the SysTick Counter Value */
  SysTick->CTRL  = SysTick_CTRL_CLKSOURCE_Msk |
                   SysTick_CTRL_TICKINT_Msk   |
                   SysTick_CTRL_ENABLE_Msk;                         /* Enable SysTick IRQ and SysTick Timer */
  return (0UL);                                                     /* Function successful */
}
#endif



void SysTick_Handler()
{

	//Tun OFF the LED
		//		*pPortIOutReg &= ~( 1 << 1);
		//3.SET 1st bit of the output data register to make I/O pin-1 as HIGH
		//	*pPortIOutReg |= ( 1 << 1);


// Toggle LED:

 *pPortIOutReg ^= ( 1 << 1);

}

